POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "blyndon",
    "password": "Sur1musique2Shubert"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "bmorin",
    "name": "Bernard Morin",
    "password": "ThispasswordisWRONG"
}
